@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.hearthstones.contents.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;