modLoader="javafml"
loaderVersion="[32,)"
license="GNU Lesser General Public License v2.1 (LGPLv2.1)"

[[mods]]
modId="hearthstones"
version="${file.jarVersion}"
displayName="Hearthstones"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tictim-hearthstones/"
logoFile="logo_400px.png"
authors="Tictim"
description='''
Build your own tavern, teleport from anywhere!
'''