@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.hearthstones.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;