@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.hearthstones.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;