@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.hearthstones.hearthstone;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;