@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.hearthstones.tavern;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;